#!/usr/bin/env bash
# set up load balancer
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy

# Make sure that HAproxy can be managed via an init script
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy

# Setup load balancing frontend and backend options
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 11792-web-01 3.228.21.63:80 check\n\tserver 11792-web-02 3.239.57.219:80 check\n' /etc/haproxy/haproxy.cfg

#restart hAproxy
sudo service haproxy restart
